apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    name: frontend
  clusterIP: None
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  serviceName: "frontend"
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:1
        env:
        - name: BASE_URL
          value: http://backend:9000
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 9000
    name: backend
  clusterIP: None
  selector:
    app: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  serviceName: "backend"
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:1
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@postgres:5432/news
        ports:
        - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  serviceName: "postgre"
  template:
    metadata:
      labels:
        app: postgre
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgre
        image: postgres:13-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: news
        volumeMounts:
        - name: postgres
          mountPath: /usr/local/pgsql/data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
